dataset: 'cs_geo_10m'

geo_10m:
  split_csv: './data/cs_geo_gse_10m/CS_Xplots_10m_curated_train_test_split.csv'
  geo_parquet: './data/cs_geo_gse_10m/CS_Xplots_embeddings_per_file_10m_public.parquet'
  image_roots:
    - './data/CS_Xplots_2019_2023_train'
    - './data/CS_Xplots_2019_2023_test'

data:
  data_split:
    valid_split: 0.15
    split_seed: 42

multimodal:
  joined_table_tag: 'gse_10m'
  fusion_mode: 'raw_concat'
  tabular_modality_name: 'geo'
  tabular_feature_columns:
    - 'A00'
    - 'A01'
    - 'A02'
    - 'A03'
    - 'A04'
    - 'A05'
    - 'A06'
    - 'A07'
    - 'A08'
    - 'A09'
    - 'A10'
    - 'A11'
    - 'A12'
    - 'A13'
    - 'A14'
    - 'A15'
    - 'A16'
    - 'A17'
    - 'A18'
    - 'A19'
    - 'A20'
    - 'A21'
    - 'A22'
    - 'A23'
    - 'A24'
    - 'A25'
    - 'A26'
    - 'A27'
    - 'A28'
    - 'A29'
    - 'A30'
    - 'A31'
    - 'A32'
    - 'A33'
    - 'A34'
    - 'A35'
    - 'A36'
    - 'A37'
    - 'A38'
    - 'A39'
    - 'A40'
    - 'A41'
    - 'A42'
    - 'A43'
    - 'A44'
    - 'A45'
    - 'A46'
    - 'A47'
    - 'A48'
    - 'A49'
    - 'A50'
    - 'A51'
    - 'A52'
    - 'A53'
    - 'A54'
    - 'A55'
    - 'A56'
    - 'A57'
    - 'A58'
    - 'A59'
    - 'A60'
    - 'A61'
    - 'A62'
    - 'A63'
  image_metadata_columns:
    - 'file'
    - 'ID'
    - 'plot_idx'
    - 'label_id'
    - 'label_name'
    - 'l2_label'
    - 'image_source'
    - 'split'
